Map errors in the delete pending segments API to proper HTTP status code.
Currently, any errors in the delete pending segments API would result
in the client not knowing about the http status and reason. This patch fixes it.

This is the error from the overlord logs that don't get mapped:
2024-01-12T01:06:41,807 ERROR [qtp1757718624-150] com.sun.jersey.spi.container.ContainerResponse - The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.IllegalArgumentException: Cannot delete pendingSegments because there is at least one active task created at 2024-01-12T01:06:41.318Z

Also, clean up the exception messages and add tests.